-----WINDOW VALUE FUNCTION-----
SELECT 
OrderDate,
Sales,
LAG(Sales) OVER(ORDER BY ORDERDATE) PREVIOUS_SALES,
LEAD(Sales) OVER(ORDER BY ORDERDATE) NEXT_SALES,
LAG(Sales, 2, 0) OVER(ORDER BY ORDERDATE) PREVIOUS_SALES,
LEAD(Sales, 2, 0) OVER(ORDER BY ORDERDATE) NEXT_SALES
FROM Sales.Orders

---------------TIME SERIES ANALYSIS
SELECT 
*,
CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES [MoM_CHANGE],
CAST(CAST(CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES AS FLOAT)/PREVIOUS_MONTH_SALES * 100 AS DECIMAL(10, 2))  [MoM_%]
FROM(
	SELECT
	MONTH(OrderDate) ORDER_MONTH,
	SUM(Sales) CURRENT_MONTH_SALES,
	LAG(SUM(Sales)) OVER(ORDER BY MONTH(OrderDate)) PREVIOUS_MONTH_SALES
	FROM Sales.Orders
	GROUP BY MONTH(OrderDate)
)T


--CUSTOMER_RETENTION_ANALYSIS
SELECT
CustomerID,
AVG(DAYS_TAKEN) AVG_DAYS,
RANK() OVER(ORDER BY ISNULL(AVG(DAYS_TAKEN), 9999999)) 
FROM(
	SELECT 
	OrderID,
	CustomerID, 
	OrderDate,
	LEAD(OrderDate) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE) NEXT_ORDER,
	DATEDIFF(DAY, OrderDate, LEAD(OrderDate) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE)) DAYS_TAKEN
	FROM Sales.Orders
) T
GROUP BY CustomerID


--FIRST_VALUE_FUNCTION

SELECT 
MONTH(OrderDate),
SUM(Sales),
FIRST_VALUE(SUM(Sales)) OVER(ORDER BY MONTH(ORDERDATE))
FROM Sales.Orders
GROUP BY MONTH(OrderDate)

--LAST_VALUE_FUNCTION
SELECT 
MONTH(OrderDate),
SUM(Sales),
LAST_VALUE(SUM(Sales)) OVER(ORDER BY MONTH(ORDERDATE))
FROM Sales.Orders
GROUP BY MONTH(OrderDate)


SELECT 
OrderID,
ProductID,
Sales,
FIRST_VALUE(Sales) OVER(PARTITION BY PRODUCTID ORDER BY SALES) LOWEST_SALES,
FIRST_VALUE(Sales) OVER(PARTITION BY PRODUCTID ORDER BY SALES DESC) HIGHEST_SALES,
MAX(Sales) OVER(PARTITION BY PRODUCTID)
FROM Sales.Orders