--CTE(COMMON TABLE EXPRESSION)
-- BASICALLY, THEY ARE VIRTUAL TABLE USED WITHIN QUERY TO SIMPIFY AND ORGANISE COMPLEX QUERY 



--RECURSIVE CTE

-------- 1.STANDALONE CTE: RUNS INDEPENDENTLY

--CTE QUERY
WITH CTE_TOTAL_SALES AS
(
	SELECT 
	CustomerID,
	SUM(SALES) [TOTAL_SALES]
	FROM Sales.Orders
	GROUP BY CustomerID
	--ORDER BY SUM(Sales) -- ORDER BY CLAUSE CAN'T BE USED IN CTE QUERY
)

--MAIN QUERY
SELECT 
C.CustomerID, 
C.FirstName,
CTS.TOTAL_SALES
FROM Sales.Customers AS C
LEFT JOIN CTE_TOTAL_SALES AS CTS
ON CTS.CustomerID = C.CustomerID
ORDER BY CTS.TOTAL_SALES DESC


-------- MULTIPLE STANDALONE CTE
--CTE QUERY
WITH CTE_TOTAL_SALES AS
(
	SELECT 
	CustomerID,
	SUM(SALES) [TOTAL_SALES]
	FROM Sales.Orders
	GROUP BY CustomerID
	--ORDER BY SUM(Sales) -- ORDER BY CLAUSE CAN'T BE USED IN CTE QUERY
)
, CTE_LAST_ORDER AS 
(
	SELECT 
	CustomerID, 
	MAX(OrderDate) [LAST_ORDER]
	FROM Sales.Orders
	GROUP BY CustomerID
)
--MAIN QUERY
SELECT 
C.CustomerID, 
C.FirstName,
CTS.TOTAL_SALES,
CTS2.LAST_ORDER
FROM Sales.Customers AS C
LEFT JOIN CTE_TOTAL_SALES AS CTS
ON CTS.CustomerID = C.CustomerID
LEFT JOIN CTE_LAST_ORDER AS CTS2
ON CTS2.CustomerID = C.CustomerID
ORDER BY CTS.TOTAL_SALES DESC




-------- NESTED CTE
--CTE QUERY
-- TOTAL SALES PER CUSTOMER
WITH CTE_TOTAL_SALES AS
(
	SELECT 
	CustomerID,
	SUM(SALES) [TOTAL_SALES]
	FROM Sales.Orders
	GROUP BY CustomerID
)
-- LAST DATE OF ORDER FOR EACH CUSTOMER
, CTE_LAST_ORDER AS 
(
	SELECT 
	CustomerID, 
	MAX(OrderDate) [LAST_ORDER]
	FROM Sales.Orders
	GROUP BY CustomerID
)
-- 2.NESTED CTE QUERY
--RANK CUSTOMER BASED ON THEIR TOTAL SALES
, CTE_CUSTOMER_RANK AS 
(
	SELECT 
	CustomerID,
	TOTAL_SALES,
	DENSE_RANK() OVER(ORDER BY TOTAL_SALES DESC) [CUST_RANK]
	FROM CTE_TOTAL_SALES
)
-- SEGMENTS CUSTOMER BASED ON THEIR TOTAL SALES
, CTE_CUSTOMER_SEGMENTS AS 
(
	SELECT 
	CustomerID,
	CASE
		WHEN TOTAL_SALES > 100 THEN 'High'
		WHEN TOTAL_SALES > 50 THEN 'Medium'
		ELSE 'Low'
	END [SEGMENTS]
	FROM CTE_TOTAL_SALES
)
--MAIN QUERY
SELECT 
C.CustomerID, 
C.FirstName,
CTS.TOTAL_SALES,
CTS2.LAST_ORDER,
CR.CUST_RANK,
CS.SEGMENTS
FROM Sales.Customers AS C
LEFT JOIN CTE_TOTAL_SALES AS CTS
ON CTS.CustomerID = C.CustomerID
LEFT JOIN CTE_LAST_ORDER AS CTS2
ON CTS2.CustomerID = C.CustomerID
LEFT JOIN CTE_CUSTOMER_RANK AS CR
ON CR.CustomerID = C.CustomerID
LEFT JOIN CTE_CUSTOMER_SEGMENTS AS CS
ON CS.CustomerID = C.CustomerID


-------- RECURSIVE CTE

-- QUES: GENERATE NUMBER 1 TO 20

WITH SERIES AS 
(
	-- ANCHOR QUERY
	SELECT 
	1 AS [MY_NUM]
	UNION ALL
	-- RECURSIVE QUERY
	SELECT 
	MY_NUM + 1
	FROM SERIES
	WHERE MY_NUM < 20
)

SELECT 
*
FROM SERIES
OPTION (MAXRECURSION 10)

-- QUES: SHOW EMPLOYEES HIERARCHY BY DISPLAYING EACHEMPLOYEES LEVEL WITHIN AN ORGANISATION

WITH EMP_HIERARCHY AS
(
	--ANCHOR QUERY
	SELECT 
	EmployeeID,
	FirstName + ISNULL(LastName, '') [FULL_NAME],
	1 AS LEVEL
	FROM Sales.Employees
	WHERE ManagerID IS NULL
	UNION ALL
	--RECURSIVE QUERY
	SELECT 
	E.EmployeeID,
	E.FirstName + ISNULL(E.LastName, '') [FULL_NAME],
	LEVEL+1 AS LEVEL
	FROM Sales.Employees AS E
	INNER JOIN EMP_HIERARCHY AS EH
	ON EH.EmployeeID = E.ManagerID
)

SELECT 
*
FROM EMP_HIERARCHY